myopic_loss_aversion/models.py
# -*- coding: utf-8 -*-
# <standard imports>
from __future__ import division
from otree.db import models
import otree.models
from otree import widgets
from otree.common import Currency as c, currency_range
import random
# </standard imports>

from django.conf import settings


doc = """
The goal of the experiment is to look how participants want to divide and
endowment between a risky asset and safe asset. The risky asset is just a
simple gamble were participants either win 7% or lose -3%. The chance that
they win is 40% and the chance that the loose is 60%. The safe asset does not
have a return so the part invested stays the same. Participants will invest
their endowment for nine rounds.
"""


source_code = "https://github.com/leliel12/otree_amelsvoort"


bibliography = ()

links = {
    "Wikipedia": {}
}

keywords = ("Myopic loss aversion", "Additive", "Multiplicative")


# =============================================================================
# CONSTANTS
# =============================================================================

class Constants:

    dev = False #settings.DEBUG

    name_in_url = 'myopic_loss_aversion'

    gadd, gmul = "additive", "multiplicative"
    gadd_endowment, gmul_endowment = c(10000), c(100000)

    sg1, sg2, sg3, sg4 = 1, 2, 3, 4
    groups = [
        (g, sg) for g in (gadd, gmul) for sg in (sg1, sg2, sg3, sg4)]

    players_per_group = None
    num_rounds = 9

    win_chance = 40
    loose_chance = 100 - win_chance
    win_perc = 7
    loose_perc = -3


# =============================================================================
# SUBSESSION
# =============================================================================

class Subsession(otree.models.BaseSubsession):

    def before_first_round(self):
        # extract and mix the players
        players = self.get_players()
        random.shuffle(players)

        # create the base for number of groups
        num_players = len(players)
        num_groups = len(Constants.groups)

        # create a list of how many players must be in every group
        # the result of this will be [2, 2, 2, 2, 2, 2, 2, 2]
        # obviously 2 * 8 = 16
        players_per_group = [int(num_players/num_groups)] * num_groups

        # add one player in order per group until the sum of size of
        # every group is equal to total of players
        idxg = 0
        while sum(players_per_group) < num_players:
            players_per_group[idxg] += 1
            idxg += 1
            if idxg >= len(players_per_group):
                idxg = 0

        # reassignment of groups
        list_of_lists = []
        for g_idx, g_size in enumerate(players_per_group):
            # it is the first group the offset is 0 otherwise we start
            # after all the players already exausted
            offset = 0 if g_idx == 0 else sum(players_per_group[:g_idx])

            # the asignation of this group end when we asign the total
            # size of the group
            limit = offset + g_size

            # we select the player to add
            group_players = players[offset:limit]
            list_of_lists.append(group_players)
        self.set_groups(list_of_lists)

    def before_session_starts(self):
        if self.round_number == 1:
            self.before_first_round()
        for idx, group in enumerate(self.get_groups()):
            group.group_type, group.subgroup_type = Constants.groups[idx]

# =============================================================================
# GROUP
# =============================================================================

class Group(otree.models.BaseGroup):

    # <built-in>
    subsession = models.ForeignKey(Subsession)
    # </built-in>

    group_type = models.CharField(
        max_length=20, choices=[Constants.gadd, Constants.gmul])

    subgroup_type = models.IntegerField(
        choices=[Constants.sg1, Constants.sg2, Constants.sg3, Constants.sg4])


# =============================================================================
# PLAYER
# =============================================================================

class Player(otree.models.BasePlayer):

    # <built-in>
    group = models.ForeignKey(Group, null=True)
    subsession = models.ForeignKey(Subsession)
    # </built-in>

    fw = models.CurrencyField(min=0)
    bet = models.PositiveIntegerField(
        min=0, max=100, widget=widgets.SliderInput())
    rt = models.FloatField()
    is_winner = models.BooleanField()

    def feedback_time(self):
        round_number = self.subsession.round_number
        if self.group.subgroup_type in (Constants.sg1, Constants.sg3):
            return True
        return round_number % 3 == 0

    def decide_time(self):
        if self.group.subgroup_type in (Constants.sg3, Constants.sg2):
            return self.subsession.round_number in (1, 4, 7)
        return True

    def gadd_payoff(self, winner, pw):
        X = Constants.gadd_endowment
        alpha_t = self.bet / 100.
        rtp = (Constants.win_perc if winner else Constants.loose_perc) / 100.
        self.payoff = float(X * (alpha_t * rtp))
        increment = X * (alpha_t * (1 + rtp) + (1 - alpha_t))
        self.fw = pw + increment

    def gmul_payoff(self, winner, pw):
        alpha_t = self.bet / 100.
        rtp = (Constants.win_perc if winner else Constants.loose_perc) / 100.
        self.payoff = float(pw * alpha_t * rtp)
        self.fw = pw * (alpha_t * (1 + rtp) + (1 - alpha_t))

    def set_payoff(self):

        # retrieve the last whealt
        fw = self.last_fw()

        # check if is winner
        self.is_winner = (
            random.randint(0, 99) <= Constants.win_chance)

        # payoff ccompute
        if self.group.group_type == Constants.gadd:
            self.gadd_payoff(self.is_winner, fw)
        else:
            self.gmul_payoff(self.is_winner, fw)

    def last_fw(self):
        previous = self.in_previous_rounds()
        first = not previous
        if first and self.group.group_type == Constants.gadd:
            return 0
        elif first and self.group.group_type == Constants.gmul:
            return Constants.gmul_endowment
        return previous[-1].fw

    def current_wealth(self):
        if self.group.subgroup_type == Constants.sg1:
            cw = self.last_fw()
        else:
            round_idx = self.subsession.round_number - 1
            if round_idx in (0, 3, 6):
                cw = self.last_fw()
            elif round_idx in (1, 2):
                players = self.in_previous_rounds()
                cw = players[0].last_fw()
            elif round_idx in (4, 5):
                players = self.in_previous_rounds()
                cw = players[3].last_fw()
            elif round_idx in (7, 8):
                players = self.in_previous_rounds()
                cw = players[6].last_fw()

        if self.group.group_type == Constants.gadd:
            cw += Constants.gadd_endowment
        return cw

    def previous_bet(self):
        if self.subsession.round_number == 1:
            return None
        return self.in_previous_rounds()[-1].bet

myopic_loss_aversion/_builtin/__init__.py
# Don't change anything in this file.
from .. import models
import otree.views
import otree.test
from otree.common import Currency as c, currency_range

class Page(otree.views.Page):
    z_models = models

    def z_autocomplete(self):
        self.subsession = models.Subsession()
        self.group = models.Group()
        self.player = models.Player()


class WaitPage(otree.views.WaitPage):

    z_models = models

    def z_autocomplete(self):
        self.subsession = models.Subsession()
        self.group = models.Group()


class Bot(otree.test.Bot):

    def z_autocomplete(self):
        self.subsession = models.Subsession()
        self.group = models.Group()
        self.player = models.Player()

myopic_loss_aversion/views.py
# -*- coding: utf-8 -*-
from __future__ import division
from . import models
from ._builtin import Page, WaitPage
from otree.common import Currency as c, currency_range
from .models import Constants

def vars_for_all_templates(self):
    return {'Constants': Constants,
            'player': self.player}


class Introduction(Page):

    def is_displayed(self):
        return self.subsession.round_number == 1

    def vars_for_template(self):
        return {}


class Decide(Page):

    def is_displayed(self):
        return True

    form_model = models.Player
    form_fields = ['bet']

    def vars_for_template(self):
        label = "In round {}, I invest".format(self.subsession.round_number)
        decide_time = self.player.decide_time()
        previous_bet = self.player.previous_bet()
        return {
            "label": label, "decide_time": decide_time,
            "previous_bet": previous_bet}

    def before_next_page(self):
        if not self.player.decide_time():
            self.player.bet = self.player.previous_bet()
        self.player.set_payoff()


class Feedback(Page):

    def is_displayed(self):
        return self.player.feedback_time()

    def vars_for_template(self):
        if self.is_displayed():
            method_name = "_sg{}_vars_for_template".format(
                self.group.subgroup_type)
            method = getattr(self, method_name)
            return method()

    def _sg1_vars_for_template(self):
        return {}

    def _sg2_vars_for_template(self):

        def rreplace(s, old, new, occurrence):
            li = s.rsplit(old, occurrence)
            return new.join(li)

        limit = self.subsession.round_number
        offset = limit - 3  # last 3 rounds

        players = self.player.in_previous_rounds() + [self.player]
        combined_payoff = sum(p.payoff for p in players[offset:limit])

        rounds = map(str, range(offset+1, limit+1))
        rounds = rreplace(", ".join(rounds), ", ", " and ", 1)

        return {"combined_payoff": combined_payoff, "rounds": rounds}

    def _sg3_vars_for_template(self):
        return {}

    def _sg4_vars_for_template(self):
        return self._sg2_vars_for_template()


class Resume(Page):

    def is_displayed(self):
        return self.subsession.round_number == Constants.num_rounds


page_sequence = [Introduction, Decide, Feedback, Resume]

myopic_loss_aversion/templates/myopic_loss_aversion/Decide.html
{% extends "global/Base.html" %}{% load staticfiles otree_tags %}{% block title %}    Round {{ player.subsession.round_number }} of {{ Constants.num_rounds }}{% endblock %}{% block content %}    <div class="row">        <div class="col-md-7">            <h3>Your Wealth:</h3>            <div class="alert alert-info">                Your wealth before round                <b>{{ player.subsession.round_number}}</b> is                <b>{{ player.current_wealth }}</b>            </div>            <div>                <h3>Your Decision:</h3>                <span>                {% if decide_time %}                    {% include 'myopic_loss_aversion/Decide/dyn.html' %}                {% else %}                    {% include 'myopic_loss_aversion/Decide/static.html' %}                {% endif %}                </span>            </div>        </div>        <div class="col-md-5">            <h3>Return Profile of the Asset</h3>            <svg width="100%" height="200">                {% include 'myopic_loss_aversion/diagram.svg' %}            </svg>        </div>    </div>    <div class="pull-right">        {% next_button %}    </div>    <br>    {% include 'myopic_loss_aversion/Instructions.html' %}    <script>        $(document).ready(function() {            var $span = $("#id_bet").siblings("span.input-group-addon");            var $value = $("#put-value-here");            $span.addClass("hide");            $span.bind("DOMSubtreeModified", function(){                var text = $span.text();                if(!!text){                    $value.text(text);                }            });            $value.text($span.text());        });    </script>    <style>        .input-group, input.form-control,        select.form-control, textarea.form-control {            width: 100% !important;            max-width: 100% !important;        }    </style>{% endblock %}

myopic_loss_aversion/templates/myopic_loss_aversion/Feedback.html
{% extends "global/Base.html" %}{% load staticfiles otree_tags %}{% block title %}    Results{% endblock %}{% block content %}<div class="row">    {% if player.group.subgroup_type == Constants.sg1 %}        {% include 'myopic_loss_aversion/Feedback/sg1.html' %}    {% elif player.group.subgroup_type == Constants.sg2 %}        {% include 'myopic_loss_aversion/Feedback/sg2.html' %}    {% elif player.group.subgroup_type == Constants.sg3 %}        {% include 'myopic_loss_aversion/Feedback/sg3.html' %}    {% elif player.group.subgroup_type == Constants.sg4 %}        {% include 'myopic_loss_aversion/Feedback/sg4.html' %}    {% endif %}</div>{% endblock %}

myopic_loss_aversion/templates/myopic_loss_aversion/Instructions.html
<style type="text/css">
    ul {
        list-style-type:circle;
        padding-left:20px;
    }
    h3.panel-sub-heading {
        padding-bottom:10px;
        padding-left:4px;
    }
</style>

<div class="well well-lg" style="padding-top:5px; padding-bottom:15px; margin-top:20px;">

    <h3 class="panel-sub-heading">Instructions</h3>

    {% if player.group.group_type == Constants.gadd %}
        {% if player.group.subgroup_type == Constants.sg1 %}
            {% include 'myopic_loss_aversion/Instructions/asg1.html' %}
        {% elif player.group.subgroup_type == Constants.sg2 %}
            {% include 'myopic_loss_aversion/Instructions/asg2.html' %}
        {% elif player.group.subgroup_type == Constants.sg3 %}
            {% include 'myopic_loss_aversion/Instructions/asg3.html' %}
        {% else %}
            {% include 'myopic_loss_aversion/Instructions/asg4.html' %}
        {% endif %}
    {% else %}
        {% if player.group.subgroup_type == Constants.sg1 %}
            {% include 'myopic_loss_aversion/Instructions/msg1.html' %}
        {% elif player.group.subgroup_type == Constants.sg2 %}
            {% include 'myopic_loss_aversion/Instructions/msg2.html' %}
        {% elif player.group.subgroup_type == Constants.sg3 %}
            {% include 'myopic_loss_aversion/Instructions/msg3.html' %}
        {% else %}
            {% include 'myopic_loss_aversion/Instructions/msg4.html' %}
        {% endif %}
    {% endif %}

    {% if Constants.dev %}
    <div class="alert alert-info">
        <p>You are in <b>{{player.group.group_type}} - {{player.group.subgroup_type}}</b> group</p>
    </div>

    {% endif %}

</div>

myopic_loss_aversion/templates/myopic_loss_aversion/Introduction.html
{% extends "global/Base.html" %}
{% load staticfiles otree_tags %}

{% block title %}
    Introduction
{% endblock %}

{% block content %}

    <p>
        In this study you will play three rounds of
        "Myopic loss aversion: Additive vs Multiplicative".
    </p>

    {% include 'myopic_loss_aversion/Instructions.html' %}

    {% next_button %}

{% endblock %}

myopic_loss_aversion/templates/myopic_loss_aversion/Resume.html
{% extends "global/Base.html" %}{% load staticfiles otree_tags %}{% block title %}    Resume{% endblock %}{% block content %}<div>    All rounds are now finished.</div><div class="well">        Your final wealth is <b>{{player.fw}}</b></div><div class="pull-right">    {% next_button %}</div>{% endblock %}